# Generated by Django 6.0.3 on 2026-03-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_project_user_alter_project_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, default='No description provided.', null=True),
        ),
    ]
