# Generated by Django 6.0.3 on 2026-03-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='_id',
        ),
    ]
